export const BASE_STUCK = [
  "TypeScript",
  "React",
  "Next.js",
  "Tailwind CSS",
  "Node.js",
  "PostgreSQL",
  "Git",
];
export const currentStack = [
  { category: "Frontend", items: ["React", "Next.js", "Svelte", "TypeScript"] },
  { category: "Backend", items: ["NestJS", "Node.js", "GraphQL", "REST"] },
  {
    category: "Database",
    items: ["Supabase", "PostgreSQL", "Redis", "MongoDB"],
  },
  { category: "Infra", items: ["Coolify", "Docker", "CI/CD", "Clickhouse"] },
  { category: "Tooling", items: ["pnpm", "Biome", "ESLint", "Prettier"] },
  {
    category: "AI & Learning",
    items: ["Claude", "Codex", "ML (Scikit-learn, PyTorch)"],
  },
];

export const legacyStack = [
  "S3",
  "firebase",
  "go",
  "clerk",
  "unity",
  "figma",
  "Apollo",
  "Redux Toolkit",
  "Redux Saga",
  "Zustand",
  "React Context",
  "Reselect",
  "React Hook Form",
  "Formik",
  "styled-components",
  "emotion",
  "CSS Modules",
  "SCSS",
  "Webpack",
  "Rollup",
  "Express",
  "TypeORM",
  "Prisma",
  "Mongoose",
  "Firebase",
  "RabbitMQ",
  "JWT",
  "Passport.js",
  "Solidity",
  "Truffle",
  "Mocha",
  "Module Federation",
  "React Native",
  "Vue",
  "Jest",
  "Yarn",
  "GitLens",
  "Jira",
  "Confluence",
  "Notion",
  "Azure",
];
